# Generated by Django 3.0.2 on 2021-07-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldetails',
            name='student_id',
            field=models.CharField(default='eeeeee', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='student_id',
            field=models.CharField(default='eeeeee', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='student_id',
            field=models.CharField(default='eeeeee', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='student_id',
            field=models.CharField(default='eeeeee', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='eeeeee', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionaldetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
