# Generated by Django 3.0.2 on 2021-07-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210730_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldetails',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='parentdetails',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
