# Generated by Django 3.0.2 on 2021-08-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210730_1522'),
        ('student', '0010_auto_20210730_1517'),
    ]

    operations = [
    ]
